# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
    ]
