# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50, verbose_name='Nome de Usuario ')),
                ('primeiro_nome', models.CharField(max_length=40, verbose_name='Primeiro Nome')),
                ('segundo_nome', models.CharField(max_length=40, verbose_name='Segundo Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
    ]
